version: '3.8'

services:
  app1:
    build: .
    container_name: app1
    expose:
      - "3000"
    environment:
      - APP_NAME=App1

  app2:
    build: .
    container_name: app2
    expose:
      - "3000"
    environment:
      - APP_NAME=App2

  app3:
    build: .
    container_name: app3
    expose:
      - "3000"
    environment:
      - APP_NAME=App3

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3